### ISSUE TITLE
Full game no Work, only Demo work

### ISSUE THREAD

**Issue by Ch3lin** [Rinnegatamante/vitaQuakeII#14]
Full game no Work, only Demo work, I have the original game, the packages for which the game is not started correctly, you can precede and the game menu appears but at the start of the game the game causes error C2-12828 and closes.

Thanks for port Quake II to the psvita :D

**Comment by Rinnegatamante** [comment]
Remove video folder from your Q2 installation.

**Comment by Ch3lin** [comment]
not have any folder whit this.... :/

**Comment by Rinnegatamante** [comment]
![immagine](https://user-images.githubusercontent.com/9152710/37365139-e8c70a38-26fc-11e8-8257-a1600d4ca442.png)

**Comment by Ch3lin** [comment]
not have this folder

![2018-03-13-163239](https://user-images.githubusercontent.com/36119214/37365589-bae70c82-26dc-11e8-8231-4ff657068316.jpg)

**Comment by Ch3lin** [comment]
Ignore me i a idiot, pack0 real size is 183.997 ... sorry for this..
