### ISSUE TITLE
Live Area, icons and Background

### ISSUE THREAD

**Issue by Ch3lin** [Rinnegatamante/vitaQuakeII#15]
As I did in Quake 1 I also wanted to contribute with the design of the Live Area and the Icon, I also leave in the package icons for possible future expansions as they did with Quake 1,
If they occupy this do **not forget to change the background**. hope you like. Thanks for your great work.
Preview:
![2018-03-13-222632](https://user-images.githubusercontent.com/36119214/37379078-b8d6f158-2710-11e8-8152-109c6047b75d.jpg)
![2018-03-13-222648](https://user-images.githubusercontent.com/36119214/37379080-b8f80514-2710-11e8-8144-46a469005eaa.jpg)

Download:
https://mega.nz/#!lbQ1RKKZ!ATNpRjhZzkAMgugxJAHRvXOJwF3Kln_lnar_pqGCet4

**Comment by Rinnegatamante** [comment]
Added with https://github.com/Rinnegatamante/vitaQuakeII/commit/5dfc6c72f40508acd13f442bc368fa3e33ce4068
Thank you!
