### ISSUE TITLE
Makefile not building vpk properly in windows

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuakeII#16]
Current makefile does not build vpk properly, it needs changed to this:

vita-make-fself -s $< build/eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE) -d ATTRIBUTE2=12 "$(TARGET)" param.sfo
	cp -f param.sfo build/sce_sys/param.sfo
	
	#------------ Comment this if you don't have 7zip ------------------
	7z a -tzip ./$(TARGET).vpk -r ./build/sce_sys ./build/eboot.bin ./build/shaders
	#-------------------------------------------------------------------

**Comment by Rinnegatamante** [comment]
I'm on windows and the Makefile works fine.

**Comment by mrdude2478** [comment]
It doesn't put the files in the proper directories in the generated vpk. If you look at the makefile you have for vitaquake - then use the same commands for vitaquakeii it will build properly, just as vitaquake now builds properly.

**Comment by Rinnegatamante** [comment]
![immagine](https://user-images.githubusercontent.com/9152710/37566937-0d2222f2-2ac0-11e8-8d46-b025eb3dfcca.png)
