### ISSUE TITLE
No water showing up?

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuakeII#17]
Firstly I have updated vitsdk/vitagl/vitaquakeii

Now the game compiles fine with no errors, it plays ok, but now when I come to a part in the game where there is supposed to be water, the water is not showing up.

I'm not sure how to screenshot on the vita so I can't show, probably the texture for water is not loading or something like that.

I'm using full game files, water works fine in your last release.

**Comment by Rinnegatamante** [comment]
Regression happened few days ago. Still have to figure out what's the cause. Btw i was already aware of the issue. Same issue affects also glass windows.

**Comment by Rinnegatamante** [comment]
Related to https://github.com/Rinnegatamante/vitaGL/issues/29
