### ISSUE TITLE
Adding ur0:/ support for "data" directory

### ISSUE THREAD

**Issue by kamilb880** [Rinnegatamante/vitaQuakeII#19]
It will be cool to have possibility to use ur0:/ partition as source for data directory - it takes most of the space that homebrew uses, and many users will be glad to have that option

**Comment by Rinnegatamante** [comment]
I think ur0: support would actually require the game to be compiled as un unsafe homebrew (don't think it's worth it). However uma0: support could be added.

**Comment by kamilb880** [comment]
Got it. If you want the confirmation, if it will require unsafe homebrew compilation I can be a tester to be sure. Just let me know

**Comment by kamilb880** [comment]
Or, if it is just a simple modification to achieve, can you just implement it with adnotation that it will work only when self compiling as unsafe homebrew?

**Comment by Rinnegatamante** [comment]
You would still need vitasdk set with vitaGL and all other dependencies to compile it.

**Comment by kamilb880** [comment]
I'll compile it by myself as unsafe homebrew, just to test if ur0: feature is working fine. 
If this is not a huge deal for you to add this option - as mentioned above, with adnotation that it will work only when self compiling from source - I'd gladly be your tester.

**Comment by kamilb880** [comment]
Just one additional thing has crossed my mind. 
Could you add possibility to use imc0: as space for "data" dir)? Just like you have mentioned adding uma0 support. 
It will not require app to be compiled as unsafe homebrew, and we'll be able to use Vita's internal storage (even on Vita 1xxx with IMCUnlock).

**Comment by Rinnegatamante** [comment]
I don't think imc0 is any different from ur0.

**Comment by Rinnegatamante** [comment]
uma0 support had been added with https://github.com/Rinnegatamante/vitaQuakeII/commit/82ef38eab2f5baf0e19f61e119b097fee3bd3746

**Comment by kamilb880** [comment]
Cool, thanks. I'll give it a try.
But regarding imc0 - it is treated by Vita as additional memory card (just like uma0), so why do you think it will be also treated as system partition, like ur0? If uma0 doesn't require "unsafe homebrew" permission, then with imc0 should be the same?

**Comment by Rinnegatamante** [comment]
You can try to replace uma0 code with imc0 and see if it works but i'm almost sure it won't.
