### ISSUE TITLE
Сan not open video setting 

### ISSUE THREAD

**Issue by Kanyka** [Rinnegatamante/vitaQuakeII#2]
When I open video settings i get error 
(C2-12828-1)

**Comment by Rinnegatamante** [comment]
Send the generated coredump file during the crash.

**Comment by Kanyka** [comment]
Oh sure.
Cannot attach it without pack to zip.
[psp2core-1505743194-0x00005b3def-eboot.bin.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/1310890/psp2core-1505743194-0x00005b3def-eboot.bin.zip)
