### ISSUE TITLE
Game is so dark

### ISSUE THREAD

**Issue by suLac4ever** [Rinnegatamante/vitaQuakeII#23]
The game is quiet dark, especially in many indoor sections and changing the gamma value doesn't seem to change anything.
v2.0
Vita slim

**Comment by Rinnegatamante** [comment]
Related to this,  a gamma change workaround can be implemented the same way it got implemented in vitaQuake meaning a quad is rendered at the end of the rendering phase with proper blend to make it alter brightness look.
Reference to the solution adopted in vitaQuake: https://www.quakewiki.net/quakesrc/121.html

**Comment by Rinnegatamante** [comment]
Solved with https://github.com/Rinnegatamante/vitaQuakeII/commit/263e9a45be27776a1b0af00a3c081de25c972d1e
