### ISSUE TITLE
FOV

### ISSUE THREAD

**Issue by suLac4ever** [Rinnegatamante/vitaQuakeII#24]
Changing the FOV to higher values (110/120) leads to invisibility of the gun.
v2.0
Vita slim

**Comment by Rinnegatamante** [comment]
That's normal.

**Comment by suLac4ever** [comment]
I've found out, that this depends on the stock quake2.exe, where it's kinda hardwired, that the gunmodel isn't drawn on a fov higher than 90. But there is a way to get rid of this quite pointless restriction:
By hex-editing the stock executable you can higher the value (which makes the weapon disapear) up to 179.
https://steamcommunity.com/sharedfiles/filedetails/?id=248035586 -> look for "See gun with wide FOV"

Wouldn't that be also possible within your port? You compile your own executable for the Vita, don't you?

**Comment by Rinnegatamante** [comment]
Weapon gets distorted with high FOV values, that's why its rendering is disabled.

**Comment by suLac4ever** [comment]
Do you think it would be possible to fix that in your port for the Vita?

**Comment by Rinnegatamante** [comment]
The distortion is already fixed with latest release in theory.

**Comment by suLac4ever** [comment]
So would removing the weapon visibility restriction at high FOV values also be possible for the Vita port?
