### ISSUE TITLE
Cannot load games since 2.0 

### ISSUE THREAD

**Issue by tboinski** [Rinnegatamante/vitaQuakeII#25]
Since the vitaQuake II 2.0 I cannot load games from previous versions.

Each time I installed the game using Vita HomeBrew Browser, no problems here. As long as I use save files from the current version everything works perfectly. Unfortunately when updated to 2.0 and later to 2.1 I am unable to load saves from the previous version. Each time the console gives c2-12828-1 error. Please find crush dump attached.

During update to 2.0 I just started from scratch, but would like to continue playing after the 2.1 update.

[psp2core-1553262853-0x00070c402d-eboot.bin.psp2dmp.gz](https://github.com/Rinnegatamante/vitaQuakeII/files/2996809/psp2core-1553262853-0x00070c402d-eboot.bin.psp2dmp.gz)

**Comment by Rinnegatamante** [comment]
Closing this cause already reported here: https://github.com/Rinnegatamante/vitaQuakeII/issues/18
