### ISSUE TITLE
vitaQuakeII v2.2 - Crash on loading "Comm Centre" level

### ISSUE THREAD

**Issue by karlos121** [Rinnegatamante/vitaQuakeII#29]
Game hard crashes when loading into "Comm Centre". I have removed all previous versions, save games, texture packs etc etc, reloaded from fresh using retail pak file and the issue persists. Using the supplied demo files on VitaDB exhibits the same issue. Attached save file and core dumps.

[vitaQuake2 dumps.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/3747347/vitaQuake2.dumps.zip)
[save.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/3747348/save.zip)

**Comment by Rinnegatamante** [comment]
When did you download the vpk? I've updated it yesterday (around 14 hrs before writing this) with a patch that should fix that specific issue. You can grab the updated executable only for quake 2 main game here: https://twitter.com/Rinnegatamante/status/1185583198069313536

**Comment by karlos121** [comment]
I downloaded and tried both the first and second revisions of 2.2 pretty much when you released them. I've checked your tweet and applied the fix eboot and tested it. Seems to be fixed. I can progress from the save file and other levels seem to be loading okay.
