### ISSUE TITLE
Crash and Workaround...

### ISSUE THREAD

**Issue by ShroomKing** [Rinnegatamante/vitaQuakeII#3]
Hey,

QuakeII has a bug that makes the game crash after beating "Big Gun" and exiting the area. making the game unfinishable.

However on PC this was easily bypassed by typing the command "map hangar1" or "map hangar1.bsp" (depends on the version) into the console to skip to the map after Big Gun  ("Outer Hangar")

This would make one loose all the collected items etc.

On vitaQuakeII you can't type in console commands into the console because there is no way to access the keyboard.  So i was wondering if you could add the option to bring up the keyboard and enter commands into the console like you have on vitaQuake(1).

Currently the only way to execute console commands in vitaQuakeII is binding them.

My workaround was modifying following binds in the config:        

bind CROSS "map hangar1"
bind CIRLCE "give all"

just to get past that crash and get my items back. This method works fine but can take up some time.

I will include the savefile from the area where the crash happens, in case you need it
[save8.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/1606151/save8.zip)  (finish the area and  escape the explosions for crash to occur)

Also it might be worth mentioning that i'm using the GOG version of QuakeII and had no problems until now.

Thanks for your patience, have a nice day!

**Comment by Rinnegatamante** [comment]
Quake Console support is definitely something that should be added.

**Comment by SHROOMKINGonDMT** [comment]
alright, i'm glad you agree!

don't feel rushed by me please, take your time and add it once you feel like it.  

i looked at how you implemented the OSK for vitaQuake and i think i might be able to add it to vitaQuakeII myself but i'm not entirely sure on everything. 

i will let you know in case i have it working

**Comment by jhardins** [comment]
Thank you very much for this, SHROOMKINGonDMT. Months after I had given up on this game, I was able to resume playing.
Some clarifications for those less savvy like myself:
As you may suspect, the config.cfg file can be accessed and modified through a file manager like VitaShell (Mine was under ux0:data/quake2/baseq2).
You’ll have to scroll down to number 69 & 70 for bind CROSS “+moveup” and bind CIRCLE “+movedown”. Take a screenshot (or refer to this post) before you modify these values to those provided by SHROOMKINGonDMT so you can reset them later. After editing a value, press the black icon with 2 downward arrows in the virtual keyboard (lower left) to confirm.
Once both entries are edited and you have SAVED the changes to config.cfg file (in VitaShell, press Circle in the directory screen to be asked if you want to save) start game and load any level.
Press X to load the next map after Big Gun.
Once loaded, press O and the game will give you all items and weapons that you will have lost, as mentioned in original post.
Save game and exit. Go back to file manager and edit the X and O values to the default ones mentioned above so you can regain the ability to jump and crouch respectively.

**Comment by shakeyjake33** [comment]
I’m getting a similar hang at the end of the area ‘Supply Station’. At the end, you have to backtrack to the previous stage but the game hangs when fling through the door. It initially just sits there, with the ‘Loading’ screen appearing after a few minutes. This then flashes and still continues to not load. I tried restarting the stage and the same issue occurred.

Unfortunately because the game hangs rather than actually crashing, there’s no error log to submit. I suppose a command console would help here, too.

**Comment by Rinnegatamante** [comment]
Implemented with https://github.com/Rinnegatamante/vitaQuakeII/commit/1fe102db1001a0176bf29db025892e0f2932c1f7
