### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by KamikazeRaven** [Rinnegatamante/vitaQuakeII#30]
Hello there,

This game does not start on my PS Vita. When I start it, the whole screen stays dark indefinitely. If I press 'start' button. It shows me an error message with the following information:

```
An error has occurred in the following application.
(C2-12812-1)
Saved Core File Succeeded.
ux0:data/psp2core-1571874581-
0x00085039b5-eboot.bin.psp2dmp
```

I jailbreaked my PS Vita following this tutorial:
[https://vita.hacks.guide/get-started](https://vita.hacks.guide/get-started)
I started with OS version 3.69. I had to update it to 3.73 to make install h-encore. I then downgraded my OS version to 3.60.

**Comment by Rinnegatamante** [comment]
You've not installed data files.
