### ISSUE TITLE
Big gun level bug

### ISSUE THREAD

**Issue by orestisns** [Rinnegatamante/vitaQuakeII#31]
Hi Rinnegatamante.
I think I found a bug in Big Gun level.
After loading that level, the game cannot be loaded/saved any more and also after finish it, the next level cannot also be loaded.
Running last version of vitaquakeII using data files from GOG.
If you need save files or any logs contact me.

Cheers

**Comment by Rinnegatamante** [comment]
If it still happens in latest public release, can you provide me a save?

**Comment by orestisns** [comment]
Its been a while since I report the bug and I deleted the save files.
However, I would like to play it again. I am curious to see if some graphics glitches have been disappeared after the release of the new vitagl.
You can keep this issue opened and I will give you an update as soon as possible.

**Comment by orestisns** [comment]
P.S.
I just saw the date that i opened this issue and the release date of latest quake 2 build. I think this is the one that had this bug.
Anyway, I will play it again, even without the latest vitagl and I will keep you updated.

**Comment by orestisns** [comment]
Hi Rinnegatamante,

I managed to reproduce the bug using the latest release (obtained from vitadb).
Hereby you can find the save files.
You can use either the "Entering big gun" save or the "The Reactor" and proceed in the next level.
[save.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/4534252/save.zip)


P.S. You will find some more save files. I observed that after the Power Plant level there are a lot of graphics glitches (especially if you are using the railgun). I thought that this might be useful if you want to see if these issues solved with the new vitagl. I won't bother you about these here.

Cheers

**Comment by Rinnegatamante** [comment]
For what concerning the railgun glitches, do those happen with this build too?
[vitaQuakeII.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/4536298/vitaQuakeII.zip)

**Comment by orestisns** [comment]
Well, when I run it using the Quake 2 button I get C2-12828-1 error (I tried using gog data files but also data files provided by vitadb).
However, if I run it using the zaero button then the quake 2 (no mods) runs fine. In addition it seems that it cannot find my save files so I don't know if the railgun issues are fixed.
I played half an hour and it looks exactly the same as before. I managed to reproduce similar graphics glitches (like the railgun) by making some explosions and also i noticed the same lightmaps issues as before.

**Comment by Rinnegatamante** [comment]
When launching mission packs, a different executable is used. This vpk has updated executable only for main game. Check out this one, should have the crash on boot fixed.
[vitaQuakeII.zip](https://github.com/Rinnegatamante/vitaQuakeII/files/4538623/vitaQuakeII.zip)

**Comment by orestisns** [comment]
GPU crash just after I run it and generates coredumps.

**Comment by Rinnegatamante** [comment]
Save bug is fixed with https://github.com/Rinnegatamante/vitaQuakeII/commit/157a4f38257baa4bc2cf3534625eef620287110c . I'm planning on dropping a new release quite soon, after release, if you still notice graphics glitches with the railgun, feel freee to open a new issue specifically for it.
