### ISSUE TITLE
Black Screen or Crash GPU (v.2.3)

### ISSUE THREAD

**Issue by once13one** [Rinnegatamante/vitaQuakeII#33]
After starting the game from the Live Area screen - black screen or crash GPU

File  attached.

version 2.2 works great

PSV Slim, HEN 3.65, Enso, SD2VITA

[psp2core-1588076326-GPUCRASH.psp2dmp.txt](https://github.com/Rinnegatamante/vitaQuakeII/files/4545731/psp2core-1588076326-GPUCRASH.psp2dmp.txt)

**Comment by Rinnegatamante** [comment]
You can fix it by placing these two files in ux0:data/quake2 : https://rinnegatamante.it/q2fix.zip

**Comment by once13one** [comment]
Thanks. Works
