### ISSUE TITLE
Build current state

### ISSUE THREAD

**Issue by DvaMishkiLapa** [Rinnegatamante/vitaQuakeII#43]
How do you gather the current state?
I get a VPK file that is 1kb in size.
![image](https://user-images.githubusercontent.com/18528109/166491909-1a9df293-10b7-4fc8-90be-7d6dcf251eb5.png)

**Comment by Sneethe** [comment]
Off Rinnegatamante website.
http://vitadb.rinnegatamante.it/#/info/278
