### ISSUE TITLE
Lots of lights/shadow issues throught the game

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/vitaQuakeII#44]
Hi @Rinnegatamante 

The game is fully completeable but there's lots of parts related to many weapons and shadows where the screen goes insane.

I can get a video / saves etc to show the worst.

But not sure since there are vitagl commits you are going to release a new build shortly and I can test that.

Thanks

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/vitaQuakeII/issues/10
