### ISSUE TITLE
Issues with newest git update

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuakeII#6]
New updates make the game incompatible with old game saves. Also the game crashes straight after a video finished (unless you press a button to skip the video). Setting brightness has no effect on the brightness and the gameplay is very dark.
Game crashes when level loading (unless you press a key to skip video loading).

I have updated vitaGL as well, and compiled with that installed.

**Comment by Rinnegatamante** [comment]
There's a motivation if stuffs are not yet released. Stop reporting issues for non released stuffs.
