### ISSUE TITLE
Mp3 Playback fix

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuakeII#7]
As in previous games, mp3 playback is not working, you can fix this by doing this:

File to edit: audiodec/cd_psp2.cpp

Line 180 :

Change From: FILE* fd = fopen(tmp,"rb");
Change To: fd = fopen(tmp,"rb");

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/vitaQuakeII/commit/691e2b52e2c66785fe5be8c2d6ad1ff12355bc6b

**Comment by mrdude2478** [comment]
Thanks very much.
